# Generated by Django 3.1.7 on 2021-03-22 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_opponent',
            new_name='player',
        ),
    ]
