# Generated by Django 3.1.7 on 2021-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_auto_20210322_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='is_over',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='game',
            table='tictactoe_game',
        ),
    ]
